### ISSUE TITLE
뉴스레터 발간형태가 이메일 & 홈페이지 둘 다 해당하는 케이스들을 업데이트해주세요

### ISSUE THREAD

**Issue by panda5176** [ryanking13/awesome-korean-newsletters#18]
[개발자스럽다](https://blog.gaerae.com/), [요즘IT](https://yozm.wishket.com/magazine/) 같은 케이스는 뉴스레터 발간형태가 현재 "이메일"로 설정되어있지만, 홈페이지로도 글을 볼 수 있습니다.
혹시 뉴스레터 발간형태에 두 가지 도메인이 다 들어가도록 바꿔주실 수 있나요...?

**Comment by ryanking13** [comment]
대부분의 이메일 뉴스레터의 경우 아카이빙 페이지 등을 통해 홈페이지를 통해서 볼 수 있는 경우가 많습니다.
그래서 굳이 두 경우를 다 명시하는 의미가 크지 않다고 생각해서 이메일로 뉴스레터를 발행하지 않는 경우만 홈페이지라고 적어두고 있는데요. (표가 너무 길어지는 것도 방지하기 위함입니다.)

혹시 더 좋은 표기 방식을 제안하시고 싶으시다면 의견 부탁드립니다!

**Comment by panda5176** [comment]
그런 이유가 있었군요 감사합니다!
